# Group Assignment: Formula 1 Data

Solve the questions regarding the `f1_data.csv` dataset. 

The full grade will be split as follows:
* 60 % notebook, code, and explanations of the questions
* 30 % presentation in class: quality of material, presentation, and Q&A
    * The presentation has to be about one specific driver, constructor, or circuit. Build a data-based history about the driver/circuit/constructor and present it.
    * You can present in any format you want: PPT, PDF, notebook, whatever
* 10 % visualization to support the answers and the presentation

The data is composed of the following variables:
* `car_number`: the number of the car
* `grid_starting_position`: the starting position of the car in the grid
* `final_position`: the position in which that driver ended
* `points`: the points earned by the driver in the race
* `laps`: the number of laps completed by the driver
* `total_race_time_ms`: the total time the driver took to complete the race in milliseconds
* `fastest_lap`: the fastest lap completed by the driver
* `rank`: the rank of the driver in the race
* `fastest_lap_time`: the time taken to complete the fastest lap
* `fastest_lap_speed`: the speed of the fastest lap
* `year`: the year of the race
* `race_number_season`: the number of the race in the season
* `race_name`: the name of the race
* `race_date`: the date of the race
* `race_start_time`: the start time of the race
* `circuit_name`: the name of the circuit where the race took place
* `circuit_location`: the location of the circuit
* `circuit_country`: the country where the circuit is located
* `circuit_lat`: the latitude of the circuit
* `circuit_lng`: the longitude of the circuit
* `circuit_altitude`: the altitude of the circuit
* `driver`: the name of the driver
* `driver_dob`: the date of birth of the driver
* `driver_nationality`: the nationality of the driver
* `constructor_name`: the name of the constructor team
* `constructor_nationality`: the nationality of the constructor team
* `status`: the status of the driver in the race (e.g., Finished, Did Not Finish, etc.)

**SUBMISSION: failing to comply with the submission format will result in a 0 grade**
* ONE (1) SINGLE ZIP FILE containing:
    * The notebook with the code and the answers
    * The presentation itself (PPT, PDF, notebook, whatever)
    * `f1_data.csv`
* The ZIP file should be named as follows: `group_assignment_<group_id>.zip`
  * For example, if you are group 1, the file should be named `group_assignment_1.zip`

### 0. Group Information

* Group ID
* Members:
  * ...

### 1. Basic operations. (1 point)

* Open the dataset as a pandas dataframe and show the first 10 rows
* Show the number of rows and columns
* Show the data types of each column
* Calculate a column called `age` which represents the age of each driver on the date of the race:
    * Hint1: use the `pd.to_datetime` function to convert the date columns to datetime
    * Hint2: use the `driver_dob` and substract from it the `race_date` column
    * Hint3: use the `dt.days` property to convert the result to days, then divide by 365.25 to get the age in years

In [1]:
# Open the dataset as a pandas dataframe and show the first 10 rows
import pandas as pd

df = pd.read_csv('f1_data.csv')
pd.set_option('display.max_columns', None)

df.head(10)

,car_number,grid_starting_position,final_position,points,laps,total_race_time_ms,fastest_lap,rank,fastest_lap_time,fastest_lap_speed,year,race_number_season,race_name,race_date,race_start_time,circuit_name,circuit_location,circuit_country,circuit_lat,circuit_lng,circuit_altitude,driver,driver_dob,driver_nationality,constructor_name,constructor_nationality,status
0,22.0,1,1.0,10.0,58,5690616.0,39.0,2.0,1:27.452,218.300,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Lewis Hamilton,1985-01-07,British,McLaren,British,Finished
1,3.0,5,2.0,8.0,58,5696094.0,41.0,3.0,1:27.739,217.586,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Nick Heidfeld,1977-05-10,German,BMW Sauber,German,Finished
2,7.0,7,3.0,6.0,58,5698779.0,41.0,5.0,1:28.090,216.719,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Nico Rosberg,1985-06-27,German,Williams,British,Finished
3,5.0,11,4.0,5.0,58,5707797.0,58.0,7.0,1:28.603,215.464,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Fernando Alonso,1981-07-29,Spanish,Renault,French,Finished
4,23.0,3,5.0,4.0,58,5708630.0,43.0,1.0,1:27.418,218.385,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Heikki Kovalainen,1981-10-19,Finnish,McLaren,British,Finished
5,8.0,13,6.0,3.0,57,NaN,50.0,14.0,1:29.639,212.974,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Kazuki Nakajima,1985-01-11,Japanese,Williams,British,+1 Lap
6,14.0,17,7.0,2.0,55,NaN,22.0,12.0,1:29.534,213.224,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Sébastien Bourdais,1979-02-28,French,Toro Rosso,Italian,Engine
7,1.0,15,8.0,1.0,53,NaN,20.0,4.0,1:27.903,217.180,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Kimi Räikkönen,1979-10-17,Finnish,Ferrari,Italian,Engine
8,4.0,2,NaN,0.0,47,NaN,15.0,9.0,1:28.753,215.100,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Robert Kubica,1984-12-07,Polish,BMW Sauber,German,Collision
9,12.0,18,NaN,0.0,43,NaN,23.0,13.0,1:29.558,213.166,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Timo Glock,1982-03-18,German,Toyota,Japanese,Accident

In [2]:
# Show the number of rows and columns
print(df.shape)

(26080, 27)

In [3]:
# Show the data types of each column
print(df.dtypes)

car_number                 float64
grid_starting_position       int64
final_position             float64
points                     float64
laps                         int64
total_race_time_ms         float64
fastest_lap                float64
rank                       float64
fastest_lap_time            object
fastest_lap_speed          float64
year                         int64
race_number_season           int64
race_name                   object
race_date                   object
race_start_time             object
circuit_name                object
circuit_location            object
circuit_country             object
circuit_lat                float64
circuit_lng                float64
circuit_altitude           float64
driver                      object
driver_dob                  object
driver_nationality          object
constructor_name            object
constructor_nationality     object
status                      object
dtype: object

In [4]:
# Calculate a column called `age` which represents the age of each driver on the date of the race

df['driver_dob'] = pd.to_datetime(df['driver_dob'])
df['race_date'] = pd.to_datetime(df['race_date'])

df['age'] = (df['race_date'] - df['driver_dob']).dt.days / 365.25

df[['age']].head(5)

         age
0  23.186858
1  30.850103
2  22.718686
3  26.631075
4  26.406571

### 2. Why do we have missing values in the `final_position` column? (1 point)

In [5]:
df[df['final_position'].isna()].sample(3)

,car_number,grid_starting_position,final_position,points,laps,total_race_time_ms,fastest_lap,rank,fastest_lap_time,fastest_lap_speed,year,race_number_season,race_name,race_date,race_start_time,circuit_name,circuit_location,circuit_country,circuit_lat,circuit_lng,circuit_altitude,driver,driver_dob,driver_nationality,constructor_name,constructor_nationality,status,age
9352,1.0,5,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,1987,14,Mexican Grand Prix,1987-10-18,NaN,Autódromo Hermanos Rodríguez,Mexico City,Mexico,19.4042,-99.0907,2227.0,Alain Prost,1955-02-24,French,McLaren,British,Collision,32.646133
7517,8.0,22,NaN,0.0,0,NaN,NaN,NaN,NaN,NaN,1990,15,Japanese Grand Prix,1990-10-21,NaN,Suzuka Circuit,Suzuka,Japan,34.8431,136.5410,45.0,Stefano Modena,1963-05-12,Italian,Brabham,British,Collision,27.444216
1532,21.0,17,NaN,0.0,13,NaN,8.0,20.0,1:30.621,210.666,2004,1,Australian Grand Prix,2004-03-07,NaN,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.9680,10.0,Zsolt Baumgartner,1981-01-01,Hungarian,Minardi,Italian,Electrical,23.178645

In [6]:
# When looking at the status for drivers with no position, they did not finish the race or disqualified 
print(list(df[df['final_position'].isna()]['status'].value_counts().index)) 
print(df[df['final_position'].isna()]['status'].value_counts())

print('Considering some of the drivers had NaN as a final position but in other columns there were values, we can assume that the missing')
print('values indicate that the driver either did not finish the race or was disqualified. We can also see according to the list that all')
print('the status values with final position as NaN, were related to not finishing the race or disqualified.')

['Engine', 'Did not qualify', 'Accident', 'Collision', 'Gearbox', 'Spun off', 'Suspension', 'Did not prequalify', 'Transmission', 'Electrical', 'Withdrew', 'Brakes', 'Clutch', 'Not classified', 'Disqualified', 'Turbo', 'Fuel system', 'Hydraulics', 'Overheating', 'Oil leak', 'Ignition', 'Throttle', 'Halfshaft', 'Retired', 'Wheel', 'Oil pressure', 'Fuel pump', 'Differential', 'Handling', 'Tyre', 'Fuel leak', 'Steering', 'Collision damage', 'Radiator', 'Power Unit', 'Puncture', 'Wheel bearing', 'Injection', 'Water leak', 'Physical', 'Fuel pressure', 'Chassis', 'Exhaust', 'Mechanical', 'Alternator', 'Driveshaft', 'Out of fuel', 'Magneto', 'Axle', 'Heat shield fire', 'Battery', 'Power loss', 'Oil pump', 'Distributor', 'Injury', 'Oil pipe', 'Driver unwell', 'Electronics', 'Broken wing', '107% Rule', 'Excluded', 'Wheel nut', 'Rear wing', 'Water pump', 'Injured', 'Vibrations', 'Water pressure', 'Supercharger', 'Front wing', '+11 Laps', 'Pneumatics', 'ERS', 'Fuel', '+9 Laps', 'Spark plugs', 'Fatal accident', '+8 Laps', '+7 Laps', 'Fire', 'Technical', 'Water pipe', '+10 Laps', 'Fuel pipe', 'Damage', 'Illness', 'Drivetrain', 'Undertray', 'Safety concerns', 'Oil line', 'Fuel rig', 'Stalled', 'Safety', '+12 Laps', 'Refuelling', 'Debris', 'Seat', 'Engine misfire', 'Brake duct', 'Driver Seat', 'Wheel rim', 'Cooling system', '+17 Laps', '+1 Lap', '+2 Laps', '+14 Laps', 'CV joint', '+42 Laps', 'Track rod', 'Safety belt', '+26 Laps', '+6 Laps', '+3 Laps', 'Launch control', 'Eye injury', 'Crankshaft', 'Not restarted', '+4 Laps', 'Underweight', 'Engine fire']
status
Engine             1878
Did not qualify    1025
Accident            976
Collision           790
Gearbox             770
                   ...
Crankshaft            1
Not restarted         1
+4 Laps               1
Underweight           1
Engine fire           1
Name: count, Length: 119, dtype: int64
Considering some of the drivers had NaN as a final position but in other columns there were values, we can assume that the missing
values indicate that the driver either did not finish the race or was disqualified. We can also see according to the list that all
the status values with final position as NaN, were related to not finishing the race or disqualified.

### 3. Constructor analytics (3 points)

* Which constructor has the most race wins? (0.5 points)
* Which constructor has the most podiums (position 1, 2, or 3)? (0.5 points)
* Which constructor has the biggest probability of not finishing a race, according to the dataset? (0.5 points)
* Which country has the most successful constructors in terms of race victories? (0.5 points)
* Which are the current constructors (from 2023) with the longest history in Formula 1? (0.5 points)
* Which is the constructor with the most drivers in Formula 1 across its history? (0.5 points)

In [7]:
# Which constructor has the most race wins? (0.5 points)
df_first_place = df[df['final_position'] == 1]
wins = df_first_place.groupby('constructor_name')['final_position'].count().sort_values(ascending = False)

print(f'{wins.idxmax()} has the most race wins at {wins.max()} wins.')

Ferrari has the most race wins at 243 wins.

In [8]:
# Which constructor has the most podiums (position 1, 2, or 3)? (0.5 points)
df_positions = df[(df['final_position'] == 1) | (df['final_position'] == 2) | (df['final_position'] == 3)]
constructor_by_positions = df_positions.groupby('constructor_name')['final_position'].count()

print(f'{constructor_by_positions.idxmax()} has the most podiums at {constructor_by_positions.max()} podiums.')

Ferrari has the most podiums at 813 podiums.

In [9]:
# Which constructor has the biggest probability of not finishing a race, according to the dataset? (0.5 points)
f1_2023 = df[df['year'] == 2023]
constructors_2023 = f1_2023['constructor_name'].unique()

last_5_years_data = df[df['year'] >= 2019]
dnf_data = last_5_years_data[last_5_years_data['final_position'].isna()]

total_races = last_5_years_data.groupby('constructor_name').size()

dnf_counts = dnf_data.groupby('constructor_name').size()

dnf_probability = dnf_counts / total_races
dnf_probability_2023 = dnf_probability.loc[constructors_2023]
sorted_dnf_probability_2023 = dnf_probability_2023.sort_values(ascending=False)

print('Due to advancements in cars, we took the data from the last 5 years to get the more advanced cars')
print(f'According to the last five years from 2023 {sorted_dnf_probability_2023.idxmax()} has the highest probability of not finishing at {round(sorted_dnf_probability_2023.max(), 2)}')

Due to advancements in cars, we took the data from the last 5 years to get the more advanced cars
According to the last five years from 2023 Haas F1 Team has the highest probability of not finishing at 0.19

In [10]:
# Which country has the most successful constructors in terms of race victories? (0.5 points)
country_victories = df_first_place.groupby('constructor_nationality')['final_position'].count()

print(f'{country_victories.idxmax()} is the country with the most successful constructors at {country_victories.max()} victories.')

British is the country with the most successful constructors at 494 victories.

In [11]:
# Which are the current constructors (from 2023) with the longest history in Formula 1? (0.5 points)
f1_2023 = df[df['year'] == 2023]
constructors_2023 = f1_2023['constructor_name'].unique()
first_year_per_constructor = df.groupby('constructor_name')['year'].min()
sorted_constructors_by_history = first_year_per_constructor.loc[constructors_2023].sort_values()

print(f'When looking at the minimum year the constructor started we find that {sorted_constructors_by_history.idxmin()} has the longest history dating back to {sorted_constructors_by_history.min()}.')
print('Alfa Romeo also started in 1950:')
print(sorted_constructors_by_history.head(2))

When looking at the minimum year the constructor started we find that Ferrari has the longest history dating back to 1950.
Alfa Romeo also started in 1950:
constructor_name
Ferrari       1950
Alfa Romeo    1950
Name: year, dtype: int64

In [12]:
# Which is the constructor with the most drivers in Formula 1 across its history? (0.5 points)
constructor_most_drivers = df.groupby('constructor_name')['driver'].nunique()

print(f'{constructor_most_drivers.idxmax()} has the most drivers at {constructor_most_drivers.max()}.')

Ferrari has the most drivers at 97.

### 4. Driver analytics (3 points)

* With the data available, who is the fastest driver in Formula 1? (0.5 point)
* Which is the driver with the most podiums without a win (position 2 or 3)? (0.5 point)
* Calculate the historical probability of each country of having a driver in the podium (0.5 point)
* Calculate the historical probability of each country of having a driver win a race (0.5 point)
* Which driver was the youngest to win a race? (0.5 point)
* Which drivers are the current ones with the longest history in Formula 1? (0.5 point)

Hint: remember that a probability is calculated as the number of times an event happened divided by the total number of events

In [13]:
#With the data available, who is the fastest driver in Formula 1? (0.5 point)
#Based on average fastest lap speed
average_race_speed = df.groupby('driver')['fastest_lap_speed'].mean()

sorted_average_race_speed = average_race_speed.sort_values(ascending=False)

sorted_average_race_speed.head()

driver
Antônio Pizzonia    224.316500
Jack Aitken         222.240000
Marc Gené           219.422500
Ricardo Zonta       219.073000
Nyck de Vries       213.475818
Name: fastest_lap_speed, dtype: float64

In [14]:
#Based on fastest lap time

import pandas as pd
import numpy as np

def time_to_seconds(time_value):
    if pd.isnull(time_value):
        return np.nan
    if isinstance(time_value, (int, float)):
        return time_value
    time_str = str(time_value)

    if ':' in time_str:
        minutes, seconds = time_str.split(':')
        total_seconds = int(minutes) * 60 + float(seconds)
        return total_seconds
    else:
        # Handle cases without a colon (just seconds)
        return float(time_str)


df['fastest_lap_seconds'] = df['fastest_lap_time'].apply(time_to_seconds)
sorted_df = df[df['fastest_lap_seconds'].notna()]

print('All drivers and thier fastest times grouped by circuits:')
print(sorted_df.groupby(['circuit_name', 'driver'])['fastest_lap_seconds'].min().sort_values(ascending = True))
print()

sorted_df = df[df['fastest_lap_seconds'].notna()]

driver_lap_times = sorted_df.groupby(['circuit_name', 'driver'])['fastest_lap_seconds'].min().reset_index()

driver_lap_times['min_time_per_circuit'] = driver_lap_times.groupby('circuit_name')['fastest_lap_seconds'].transform('min')

fastest_drivers = driver_lap_times[driver_lap_times['fastest_lap_seconds'] == driver_lap_times['min_time_per_circuit']]

fastest_drivers = fastest_drivers.drop(columns='min_time_per_circuit')

print('The fastest driver and their fastest time grouped by circuit:')
sorted_fastest_drivers = fastest_drivers[['circuit_name', 'driver', 'fastest_lap_seconds']].sort_values(by = 'fastest_lap_seconds', ascending = True)
print(sorted_fastest_drivers.head(3))
print()

print('The number of times a drver appears as the fastest across all circuits:')
most_appearing_drivers = sorted_fastest_drivers['driver'].value_counts()
print(most_appearing_drivers.head(3))
print()

print(f'{most_appearing_drivers.idxmax()} appears the most as the fastest driver across {most_appearing_drivers.max()} different circuits.')

All drivers and thier fastest times grouped by circuits:
circuit_name                          driver
Bahrain International Circuit         George Russell         55.404
                                      Valtteri Bottas        56.563
                                      Sergio Pérez           56.789
                                      Antonio Giovinazzi     56.887
                                      Sebastian Vettel       56.905
                                                             ...
Autodromo Internazionale del Mugello  Nicholas Latifi       131.365
                                      Esteban Ocon          131.793
                                      Antonio Giovinazzi    133.809
                                      Kevin Magnussen       133.812
                                      Carlos Sainz          134.103
Name: fastest_lap_seconds, Length: 2145, dtype: float64

The fastest driver and their fastest time grouped by circuit:
                       circuit_name              driver  fastest_lap_seconds
417   Bahrain International Circuit      George Russell               55.404
1616                  Red Bull Ring        Carlos Sainz               65.619
1286    Indianapolis Motor Speedway  Rubens Barrichello               70.399

The number of times a drver appears as the fastest across all circuits:
driver
Lewis Hamilton      9
Max Verstappen      4
Sebastian Vettel    4
Name: count, dtype: int64

Lewis Hamilton appears the most as the fastest driver across 9 different circuits.

In [15]:
# Which is the driver with the most podiums without a win (position 2 or 3)? (0.5 point)
podium_finishes = df[df['final_position'].isin([2, 3])]

drivers_no_wins = df.groupby('driver')['final_position'].apply(lambda x: 1 not in x.values)

podium_no_wins = podium_finishes[podium_finishes['driver'].isin(drivers_no_wins[drivers_no_wins].index)]

podium_counts = podium_no_wins['driver'].value_counts()

print(podium_counts.head(3))

print(f'{podium_counts.idxmax()} has the most podiums ({podium_counts.max()}) without a win.')

driver
Nick Heidfeld       13
Stefan Johansson    12
Chris Amon          11
Name: count, dtype: int64
Nick Heidfeld has the most podiums (13) without a win.

In [16]:
#Calculate the historical probability of each country of having a driver in the podium (0.5 point)
print('When looking at a countries entire history of races:')
print(df.groupby('driver_nationality')['final_position'].apply(lambda x: ((x == 1) | (x == 2) | (x == 3)).sum() / x.size).sort_values(ascending=False).head(3))
print()

print('When looking at a countries grouped by the year to see overtime.')
print(df.groupby(['driver_nationality', 'year'])['final_position'].apply(lambda x: ((x == 1) | (x == 2) | (x == 3)).sum() / x.size))

print('Second Method:')
podium_finishes = df[df['final_position'].isin([1, 2, 3])]

country_podium_counts = podium_finishes.groupby('driver_nationality')['final_position'].count()

total_race_counts = df.groupby('driver_nationality')['final_position'].count()

country_podium_probability = (country_podium_counts / total_race_counts) * 100 

sorted_podium_probabilities = country_podium_probability.sort_values(ascending=False)

sorted_podium_probabilities.head(3)

When looking at a countries entire history of races:
driver_nationality
Argentine    0.262735
Colombian    0.240000
Finnish      0.211389
Name: final_position, dtype: float64

When looking at a countries grouped by the year to see overtime.
driver_nationality  year
American            1950    0.081081
                    1951    0.105263
                    1952    0.081081
                    1953    0.068966
                    1954    0.045455
                              ...
Venezuelan          2011    0.000000
                    2012    0.050000
                    2013    0.000000
                    2014    0.000000
                    2015    0.000000
Name: final_position, Length: 1031, dtype: float64
Second Method:

driver_nationality
Argentine        47.115385
Colombian        44.776119
South African    31.858407
Name: final_position, dtype: float64

In [17]:
# Calculate the historical probability of each country of having a driver win a race (0.5 point)
print('When looking at their a countries entire history of races:')
print(df.groupby('driver_nationality')['final_position'].apply(lambda x: (x == 1).sum() / x.size).sort_values(ascending=False).head(3))
print()

print('When looking at a countries grouped by the year to see overtime.')
print(df.groupby(['driver_nationality', 'year'])['final_position'].apply(lambda x: (x == 1).sum() / x.size))
print()

print('Second Method:')
race_wins = df[df['final_position'] == 1]

country_race_win_counts = race_wins.groupby('driver_nationality')['final_position'].count()
total_race_counts = df.groupby('driver_nationality')['final_position'].count()

country_win_probability = (country_race_win_counts / total_race_counts) * 100 

sorted_win_probabilities = country_win_probability.sort_values(ascending=False)
print(sorted_win_probabilities.head(3))

When looking at their a countries entire history of races:
driver_nationality
Argentine    0.101877
Dutch        0.089641
German       0.074708
Name: final_position, dtype: float64

When looking at a countries grouped by the year to see overtime.
driver_nationality  year
American            1950    0.027027
                    1951    0.026316
                    1952    0.027027
                    1953    0.017241
                    1954    0.015152
                              ...
Venezuelan          2011    0.000000
                    2012    0.050000
                    2013    0.000000
                    2014    0.000000
                    2015    0.000000
Name: final_position, Length: 1031, dtype: float64

Second Method:
driver_nationality
Argentine    18.269231
Dutch        14.657980
British      11.981388
Name: final_position, dtype: float64

In [18]:
# Which driver was the youngest to win a race? (0.5 point)
df_wins = df[df['final_position'] == 1]

df_wins[['driver', 'final_position', 'age', 'year']].loc[df_wins['age'].idxmin()]

driver            Max Verstappen
final_position               1.0
age                    18.622861
year                        2016
Name: 23000, dtype: object

In [19]:
# Which drivers are the current ones with the longest history in Formula 1? (0.5 point)
driver_career_dates = df.groupby('driver')['race_date'].agg(['min', 'max']).reset_index()
driver_career_dates.rename(columns = {'min': 'first_race', 'max': 'last_race'}, inplace = True)

driver_career_dates['career_duration_years'] = (driver_career_dates['last_race'] - driver_career_dates['first_race']).dt.days / 365.25

driver_career_dates['race_count'] = df.groupby('driver').size().reset_index(name = 'race_count')['race_count']

driver_career_dates['avg_race_per_year'] = driver_career_dates['race_count'] / driver_career_dates['career_duration_years'].replace(0, 1)

driver_career_dates.sort_values(by = 'avg_race_per_year', ascending = False)

# Filter Drivers with career lasting under a year

print('When basing it off of the range of the drivers first race and their last race:')
print(driver_career_dates[['driver', 'career_duration_years']].sort_values(by = 'career_duration_years', ascending = False).iloc[0])
print()

print('When basing it off of the number of races in their career:')
print(driver_career_dates[['driver', 'race_count']].sort_values(by = 'race_count', ascending = False).iloc[0])
print()

print('When basing it off of both having both the longest career and most races:')
print(driver_career_dates[['driver', 'career_duration_years', 'race_count']].sort_values(['career_duration_years', 'race_count'], ascending = False).iloc[0])

When basing it off of the range of the drivers first race and their last race:
driver                   Fernando Alonso
career_duration_years          22.403833
Name: 256, dtype: object

When basing it off of the number of races in their career:
driver        Fernando Alonso
race_count                370
Name: 256, dtype: object

When basing it off of both having both the longest career and most races:
driver                   Fernando Alonso
career_duration_years          22.403833
race_count                           370
Name: 256, dtype: object

### 5. Circuit analytics (2 points)

* Which would you say is the toughest circuit in Formula 1? (0.5 point)
* Which circuit requires the most f1 experience to win? (0.5 point)
* Which circuit and year saw the most number of non-finishers? (0.5 point)
* For each constructor, which is their best circuit in terms of amount of podiums? (0.5 point)

In [20]:
# Which would you say is the toughest circuit in Formula 1? (0.5 point)
df_not_finished = df[df['final_position'].isna()]

dnf = df_not_finished.groupby('circuit_name')['status'].size().reset_index().sort_values(by = 'status', ascending = False)
print(f'The circuit with the highest number of DNFs: \n{dnf.iloc[0]}')
print()

dnf_data = df[df['final_position'].isna()]

circuit_dnf_counts = dnf_data.groupby('circuit_name')['final_position'].size()
circuit_race_counts = df.groupby('circuit_name')['final_position'].size()

circuit_dnf_rate = (circuit_dnf_counts / circuit_race_counts) * 100 
sorted_dnf_rate = circuit_dnf_rate.sort_values(ascending=False).reset_index().rename(columns = {'final_position': 'dnf_percentage'})
print(f'If we put that into percentges of DNFs compared to races: \n{sorted_dnf_rate.iloc[0]}')

The circuit with the highest number of DNFs:
circuit_name    Circuit de Monaco
status                        854
Name: 25, dtype: object

If we put that into percentges of DNFs compared to races:
circuit_name      Fair Park
dnf_percentage    69.230769
Name: 0, dtype: object

In [21]:
#Which circuit requires the most f1 experience to win? (0.5 point)
winning_drivers = df[df['final_position'] == 1]

driver_first_year = df.groupby('driver')['year'].min()
winning_drivers = winning_drivers.merge(driver_first_year, on='driver', how='left', suffixes=('', '_first'))
winning_drivers['career_span_at_win'] = winning_drivers['year'] - winning_drivers['year_first'] 

circuit_experience_at_win = winning_drivers.groupby('circuit_name')['career_span_at_win'].mean()
sorted_circuit_experience_at_win = circuit_experience_at_win.sort_values(ascending=False).reset_index().rename(columns = {'career_span_at_win': 'avg_career_span_at_win_years'})
print(f'The circuit requiring the most experience to place first:\n{sorted_circuit_experience_at_win.iloc[0]}')

The circuit requiring the most experience to place first:
circuit_name                    Losail International Circuit
avg_career_span_at_win_years                            14.0
Name: 0, dtype: object

In [22]:
# Which circuit and year saw the most number of non-finishers? (0.5 point)
no_finish = df[df['final_position'].isna()]

print('Most non-finishers across all years:')
print(no_finish.groupby('circuit_name')['final_position'].size().reset_index().sort_values(by = 'final_position', ascending = False).iloc[0])
print()

print('When looking at non finishers, we included the year as earlier car models might have been more prone to breakdown or other issues.')
print(f'With this in mind we found that this was further proven with the most DNFs in 1989')
no_finish.groupby(['circuit_name', 'year'])['final_position'].size().reset_index().sort_values(by = 'final_position', ascending = False)

Most non-finishers across all years:
circuit_name      Circuit de Monaco
final_position                  854
Name: 25, dtype: object

When looking at non finishers, we included the year as earlier car models might have been more prone to breakdown or other issues.
With this in mind we found that this was further proven with the most DNFs in 1989

                  circuit_name  year  final_position
5      Adelaide Street Circuit  1989              31
314  Circuit Gilles Villeneuve  1989              31
830     Phoenix street circuit  1989              30
994             Suzuka Circuit  1989              29
463          Circuit de Monaco  1990              28
..                         ...   ...             ...
679                Hungaroring  2019               1
676                Hungaroring  2016               1
572    Circuit of the Americas  2013               1
869              Red Bull Ring  2023               1
492          Circuit de Monaco  2019               1

[1072 rows x 3 columns]

In [23]:
# For each constructor, which is their best circuit in terms of amount of podiums? (0.5 point)
df_podiums = df[df['final_position'].isin([1, 2, 3])]

constructor_circuit = df_podiums.groupby(['constructor_name', 'circuit_name'])['final_position'].size().reset_index(name = 'podium_count')
constructor_circuit
constructor_circuit.loc[constructor_circuit.groupby('constructor_name')['podium_count'].idxmax()].sort_values(by = 'podium_count', ascending = False)

    constructor_name                   circuit_name  podium_count
201          Ferrari   Autodromo Nazionale di Monza            73
421          McLaren   Autodromo Nazionale di Monza            28
734         Williams                 Hockenheimring            21
301     Kurtis Kraft    Indianapolis Motor Speedway            19
511         Mercedes            Silverstone Circuit            19
..               ...                            ...           ...
192    Eagle-Weslake   Circuit de Spa-Francorchamps             1
189          Dallara  Autodromo Enzo e Dino Ferrari             1
516             Onyx           Autódromo do Estoril             1
517           Penske                   Brands Hatch             1
306     Leyton House            Circuit Paul Ricard             1

[76 rows x 3 columns]

## Code for the presentation goes here

Build a data-based history about a driver/circuit/constructor and present it using your preferred format. You can use any of the data available in the dataset.

Examples:
* The most successful driver in Formula 1 history
* Why Monaco is the most difficult circuit in Formula 1
* The history of Ferrari in Formula 1
* ...

In [47]:
df_cleaned = df[['driver']].copy()
df_cleaned = df_cleaned.dropna()

driver_row_counts_corrected = df_cleaned['driver'].value_counts().reset_index()
driver_row_counts_corrected.columns = ['driver', 'row_count']
driver_row_counts_corrected_sorted = driver_row_counts_corrected.sort_values(by='row_count', ascending=False).reset_index(drop=True)

print('Number of races per driver:')
print(driver_row_counts_corrected_sorted.head())

Number of races per driver:
               driver  row_count
0     Fernando Alonso        370
1      Kimi Räikkönen        352
2  Rubens Barrichello        326
3      Lewis Hamilton        322
4       Jenson Button        309

In [50]:
df_filtered = df[['driver', 'constructor_name', 'race_name', 'final_position', 'year']].copy()
df_filtered['final_position'] = pd.to_numeric(df_filtered['final_position'], errors='coerce').fillna(24) # Replace NaN in 'final_position' with 24 (for non-finishers)

# Combine race_name and year to create a unique race identifier
df_filtered['unique_race'] = df_filtered['race_name'].astype(str) + "_" + df_filtered['year'].astype(str)

# Function to compare drivers within a group
def calculate_better_finishes(group):
    group = group.sort_values('final_position').reset_index(drop=True)
    group['better_than_teammate'] = group['final_position'] < group['final_position'].shift(-1)
    return group

# Group by unique_race and constructor_name to compare teammates
df_comparison = df_filtered.groupby(['unique_race', 'constructor_name']).apply(calculate_better_finishes)

# Count the number of races where a driver finished better than their teammate
driver_better_counts = df_comparison.groupby('driver')['better_than_teammate'].sum().reset_index()

driver_better_counts.columns = ['driver', 'better_than_teammate_count']
driver_better_counts = driver_better_counts.sort_values(by='better_than_teammate_count', ascending=False).reset_index(drop=True)

print(driver_better_counts.head(10))

               driver  better_than_teammate_count
0     Fernando Alonso                         241
1      Lewis Hamilton                         199
2  Michael Schumacher                         193
3    Sebastian Vettel                         178
4      Kimi Räikkönen                         175
5       Jenson Button                         161
6  Rubens Barrichello                         121
7      Max Verstappen                         118
8    Daniel Ricciardo                         115
9        Sergio Pérez                         111

In [54]:
driver_combined = driver_row_counts_corrected_sorted.merge(driver_better_counts, on='driver', how='inner')


driver_combined['percentage_above_teammate'] = (driver_combined['better_than_teammate_count'] / driver_combined['row_count'] * 100)
driver_combined = driver_combined.sort_values(by='percentage_above_teammate', ascending=False).reset_index(drop=True)

driver_combined.head(20)

,driver,row_count,better_than_teammate_count,percentage_above_teammate
0,Dennis Poore,2,2,100.0
1,Alberto Rodriguez Larreta,1,1,100.0
2,Larry Crockett,1,1,100.0
3,Don Beauman,1,1,100.0
4,Chuck Arnold,1,1,100.0
5,Peter Broeker,1,1,100.0
6,Oscar Gálvez,1,1,100.0
7,Jonathan Williams,1,1,100.0
8,John Barber,1,1,100.0
9,Robert La Caze,1,1,100.0
10,George Amick,1,1,100.0
11,Guy Tunmer,1,1,100.0
12,André Guelfi,1,1,100.0
13,Heini Walter,1,1,100.0
14,Luiz Bueno,1,1,100.0
15,Warwick Brown,1,1,100.0
16,Peter Ashdown,1,1,100.0
17,Fritz Riess,1,1,100.0
18,Helmut Niedermayr,1,1,100.0
19,Johnny Mantz,1,1,100.0

In [58]:
# Filter drivers with more than 45 races
drivers_with_min_races_46 = driver_row_counts_corrected_sorted[driver_row_counts_corrected_sorted['row_count'] > 45]

# Teammate Comparison DataFrame
df_filtered = df[['driver', 'constructor_name', 'race_name', 'final_position', 'year']].copy()
df_filtered['final_position'] = pd.to_numeric(df_filtered['final_position'], errors='coerce').fillna(24)
df_filtered['unique_race'] = df_filtered['race_name'].astype(str) + "_" + df_filtered['year'].astype(str)


def calculate_better_finishes(group):
    group = group.sort_values('final_position').reset_index(drop=True)
    group['better_than_teammate'] = group['final_position'] < group['final_position'].shift(-1)
    return group


df_comparison = df_filtered.groupby(['unique_race', 'constructor_name']).apply(calculate_better_finishes)
driver_better_counts = df_comparison.groupby('driver')['better_than_teammate'].sum().reset_index()
driver_better_counts.columns = ['driver', 'better_than_teammate_count']

driver_combined = drivers_with_min_races_46.merge(driver_better_counts, on='driver', how='inner')

driver_combined['percentage_above_teammate'] = (driver_combined['better_than_teammate_count'] / driver_combined['row_count'] * 100)
driver_combined = driver_combined.sort_values(by='percentage_above_teammate', ascending=False).reset_index(drop=True)

driver_combined.head(10)

,driver,row_count,better_than_teammate_count,percentage_above_teammate
0,Juan Fangio,58,40,68.965517
1,Max Verstappen,175,118,67.428571
2,Fernando Alonso,370,241,65.135135
3,Michael Schumacher,308,193,62.662338
4,Mike Hawthorn,48,30,62.500000
5,Lewis Hamilton,322,199,61.801242
6,Jim Clark,73,45,61.643836
7,Richie Ginther,54,33,61.111111
8,Lando Norris,94,57,60.638298
9,George Russell,94,57,60.638298

In [61]:
# Define the points mapping according to the current F1 system
points_mapping = {
    1: 25,
    2: 18,
    3: 15,
    4: 12,
    5: 10,
    6: 8,
    7: 6,
    8: 4,
    9: 2,
    10: 1
}

# Apply the points system to create the corrected_points column
df['corrected_points'] = df['final_position'].map(points_mapping).fillna(0).astype(int)
print(df[['driver', 'final_position', 'corrected_points']].head())

              driver  final_position  corrected_points
0     Lewis Hamilton             1.0                25
1      Nick Heidfeld             2.0                18
2       Nico Rosberg             3.0                15
3    Fernando Alonso             4.0                12
4  Heikki Kovalainen             5.0                10

In [62]:
# DF with corrected points
df.head(3)

,car_number,grid_starting_position,final_position,points,laps,total_race_time_ms,fastest_lap,rank,fastest_lap_time,fastest_lap_speed,year,race_number_season,race_name,race_date,race_start_time,circuit_name,circuit_location,circuit_country,circuit_lat,circuit_lng,circuit_altitude,driver,driver_dob,driver_nationality,constructor_name,constructor_nationality,status,age,fastest_lap_seconds,corrected_points
0,22.0,1,1.0,10.0,58,5690616.0,39.0,2.0,1:27.452,218.300,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Lewis Hamilton,1985-01-07,British,McLaren,British,Finished,23.186858,87.452,25
1,3.0,5,2.0,8.0,58,5696094.0,41.0,3.0,1:27.739,217.586,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Nick Heidfeld,1977-05-10,German,BMW Sauber,German,Finished,30.850103,87.739,18
2,7.0,7,3.0,6.0,58,5698779.0,41.0,5.0,1:28.090,216.719,2008,1,Australian Grand Prix,2008-03-16,04:30:00,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10.0,Nico Rosberg,1985-06-27,German,Williams,British,Finished,22.718686,88.090,15

In [37]:
# Group by driver to calculate total corrected points and total races
driver_performance_ratio = df.groupby('driver').agg(
    total_corrected_points = ('corrected_points', 'sum'),
    total_races = ('driver', 'count') 
).reset_index()

driver_performance_ratio = driver_performance_ratio[driver_performance_ratio['total_races'] > 45]

# Calculate the ratio of corrected points to total races
driver_performance_ratio['ratio_points_per_race'] = (
    driver_performance_ratio['total_corrected_points'] / (driver_performance_ratio['total_races'] * 25)
)

driver_performance_ratio = driver_performance_ratio.sort_values(by='ratio_points_per_race', ascending=False).reset_index(drop=True)

driver_performance_ratio.head(30)

,driver,total_corrected_points,total_races,ratio_points_per_race
0,Lewis Hamilton,4879,322,0.606087
1,Juan Fangio,873,58,0.602069
2,Max Verstappen,2266,175,0.517943
3,Michael Schumacher,3890,308,0.505195
4,Alain Prost,2483,202,0.491683
5,Ayrton Senna,1881,162,0.464444
6,Jim Clark,839,73,0.459726
7,Jackie Stewart,1109,100,0.443600
8,Sebastian Vettel,3287,300,0.438267
9,Mike Hawthorn,463,48,0.385833
10,Damon Hill,1091,122,0.357705
11,Juan Pablo Montoya,825,95,0.347368
12,Nico Rosberg,1739,206,0.337670
13,Stirling Moss,616,73,0.337534
14,Denny Hulme,940,112,0.335714
15,Mika Häkkinen,1382,165,0.335030
16,Valtteri Bottas,1761,213,0.330704
17,Fernando Alonso,3044,370,0.329081
18,Charles Leclerc,934,115,0.324870
19,Nelson Piquet,1678,207,0.324251
20,Jody Scheckter,896,113,0.317168
21,Kimi Räikkönen,2791,352,0.317159
22,Nigel Mansell,1509,192,0.314375
23,Richie Ginther,422,54,0.312593
24,Carlos Reutemann,1131,146,0.309863
25,Niki Lauda,1341,174,0.308276
26,Bruce McLaren,755,103,0.293204
27,Jack Brabham,939,129,0.291163
28,Phil Hill,367,52,0.282308
29,David Coulthard,1726,247,0.279514

In [67]:
# Updated where drivers beat all teammates
df_comparison = df_filtered.groupby(['unique_race', 'constructor_name']).apply(calculate_better_finishes)

driver_wins_against_teammates = df_comparison[df_comparison['better_than_teammate']].groupby('driver').size().reset_index(name='wins_against_teammates')
driver_wins_against_teammates = driver_wins_against_teammates.sort_values(by='wins_against_teammates', ascending=False).reset_index(drop=True)

# Calculate the count of times each driver appears in the dataset
driver_appearance_count = df['driver'].value_counts().reset_index()
driver_appearance_count.columns = ['driver', 'total_appearances']

# Filter for drivers with more than 45 appearances
drivers_with_min_races = driver_appearance_count[driver_appearance_count['total_appearances'] > 100]


driver_wins_against_teammates = driver_wins_against_teammates.merge(drivers_with_min_races, on='driver', how='inner')

# Ratio of wins against teammates to total appearances
driver_wins_against_teammates['win_ratio'] = (
    driver_wins_against_teammates['wins_against_teammates'] /
    driver_wins_against_teammates['total_appearances']
)

driver_wins_against_teammates = driver_wins_against_teammates.sort_values(by='win_ratio', ascending=False).reset_index(drop=True)

driver_wins_against_teammates.head(30)

,driver,wins_against_teammates,total_appearances,win_ratio
0,Max Verstappen,118,175,0.674286
1,Fernando Alonso,241,370,0.651351
2,Michael Schumacher,193,308,0.626623
3,Lewis Hamilton,199,322,0.618012
4,Sebastian Vettel,178,300,0.593333
5,Ayrton Senna,92,162,0.567901
6,Pierre Gasly,67,120,0.558333
7,Charles Leclerc,64,115,0.556522
8,Alain Prost,109,202,0.539604
9,Ronnie Peterson,66,123,0.536585
10,Bruce McLaren,55,103,0.533981
11,Nico Rosberg,108,206,0.524272
12,Jenson Button,161,309,0.521036
13,Mika Salo,57,111,0.513514
14,Jack Brabham,66,129,0.511628
15,Denny Hulme,57,112,0.508929
16,Nick Heidfeld,93,184,0.505435
17,Nelson Piquet,103,207,0.497585
18,Kimi Räikkönen,175,352,0.497159
19,Daniel Ricciardo,115,234,0.491453
20,Heikki Kovalainen,55,112,0.491071
21,Carlos Reutemann,71,146,0.486301
22,Carlos Sainz,85,175,0.485714
23,Graham Hill,86,179,0.480447
24,Mika Häkkinen,79,165,0.478788
25,Nico Hülkenberg,91,196,0.464286
26,Jean Alesi,93,202,0.460396
27,Heinz-Harald Frentzen,73,159,0.459119
28,Kevin Magnussen,69,154,0.448052
29,Esteban Ocon,55,123,0.447154

In [65]:
# Merge the two DataFrames on the 'driver' column
combined_df = driver_performance_ratio.merge(
    driver_wins_against_teammates[['driver', 'win_ratio']],
    on='driver',
    how='inner'
)

# Create a new column for the multiplication of ratio_points_per_race and win_ratio
combined_df['combined_metric'] = combined_df['ratio_points_per_race'] * combined_df['win_ratio']

# Sort by the combined_metric in descending order
combined_df = combined_df.sort_values(by='combined_metric', ascending=False).reset_index(drop=True)

# Display the resulting DataFrame
print(combined_df[['driver', 'ratio_points_per_race', 'win_ratio', 'combined_metric']].head(30))

                driver  ratio_points_per_race  win_ratio  combined_metric
0       Lewis Hamilton               0.606087   0.618012         0.374569
1       Max Verstappen               0.517943   0.674286         0.349241
2   Michael Schumacher               0.505195   0.626623         0.316567
3          Alain Prost               0.491683   0.539604         0.265314
4         Ayrton Senna               0.464444   0.567901         0.263759
5     Sebastian Vettel               0.438267   0.593333         0.260038
6      Fernando Alonso               0.329081   0.651351         0.214347
7      Charles Leclerc               0.324870   0.556522         0.180797
8         Nico Rosberg               0.337670   0.524272         0.177031
9          Denny Hulme               0.335714   0.508929         0.170855
10       Nelson Piquet               0.324251   0.497585         0.161342
11       Mika Häkkinen               0.335030   0.478788         0.160408
12      Kimi Räikkönen               0.317159   0.497159         0.157679
13       Bruce McLaren               0.293204   0.533981         0.156565
14          Damon Hill               0.357705   0.434426         0.155396
15    Carlos Reutemann               0.309863   0.486301         0.150687
16        Jack Brabham               0.291163   0.511628         0.148967
17     Valtteri Bottas               0.330704   0.408451         0.135076
18          Niki Lauda               0.308276   0.436782         0.134649
19     Ronnie Peterson               0.237724   0.536585         0.127559
20       Jenson Button               0.239353   0.521036         0.124711
21      Jody Scheckter               0.317168   0.389381         0.123499
22       Nigel Mansell               0.314375   0.375000         0.117891
23         Graham Hill               0.235307   0.480447         0.113053
24         Mark Webber               0.251060   0.442396         0.111068
25    Daniel Ricciardo               0.221880   0.491453         0.109044
26     David Coulthard               0.279514   0.388664         0.108637
27     Ralf Schumacher               0.243556   0.444444         0.108247
28      Gerhard Berger               0.269905   0.380952         0.102821
29          Alan Jones               0.241709   0.418803         0.101229